In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Library berhasil diimpor")

Library berhasil diimpor

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving diabetes.csv to diabetes.csv

In [ ]:
df = pd.read_csv("/content/diabetes.csv")

print("Data berhasil dibaca")
print("Jumlah baris:", len(df))
print("Jumlah kolom:", len(df.columns))

df.head()

Data berhasil dibaca
Jumlah baris: 34
Jumlah kolom: 50

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [ ]:
# Menyimpan salinan data asli
df_awal = df.copy()

# Mengubah tanda ? menjadi data kosong
df = df.replace("?", np.nan)

print("Jumlah data kosong:")
print(df.isnull().sum())

print("\nJumlah seluruh data kosong:")
print(df.isnull().sum().sum())

print("\nJumlah baris duplikat:")
print(df.duplicated().sum())

Jumlah data kosong:
encounter_id                 0
patient_nbr                  0
race                         3
gender                       0
age                          0
weight                      34
admission_type_id            0
discharge_disposition_id     0
admission_source_id          0
time_in_hospital             0
payer_code                  34
medical_specialty           25
num_lab_procedures           0
num_procedures               0
num_medications              0
number_outpatient            0
number_emergency             0
number_inpatient             0
diag_1                       0
diag_2                       1
diag_3                       1
number_diagnoses             0
max_glu_serum               34
A1Cresult                   33
metformin                    0
repaglinide                  0
nateglinide                  0
chlorpropamide               0
glimepiride                  0
acetohexamide                0
glipizide                    0
glyburide                    0
tolbutamide                  0
pioglitazone                 0
rosiglitazone                0
acarbose                     0
miglitol                     0
troglitazone                 0
tolazamide                   0
examide                      0
citoglipton                  0
insulin                      0
glyburide-metformin          0
glipizide-metformin          0
glimepiride-pioglitazone     0
metformin-rosiglitazone      0
metformin-pioglitazone       0
change                       0
diabetesMed                  0
readmitted                   0
dtype: int64

Jumlah seluruh data kosong:
165

Jumlah baris duplikat:
0

/tmp/ipykernel_7699/1662658926.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace("?", np.nan)

In [ ]:
# Memisahkan kolom numerik dan kategorikal
kolom_numerik = df.select_dtypes(
    include=["number"]
).columns

kolom_kategori = df.select_dtypes(
    include=["object", "category", "bool"]
).columns

# Mengisi data kosong pada kolom numerik
for kolom in kolom_numerik:
    if df[kolom].isnull().any():
        median = df[kolom].median()

        if pd.notna(median):
            df[kolom] = df[kolom].fillna(median)

# Mengisi data kosong pada kolom kategorikal
for kolom in kolom_kategori:
    if df[kolom].isnull().any():
        modus = df[kolom].mode()

        if not modus.empty:
            df[kolom] = df[kolom].fillna(modus[0])

print("Proses pengisian data selesai")

Proses pengisian data selesai

In [ ]:
print("Data kosong sebelum preprocessing:")
print(df_awal.replace("?", np.nan).isnull().sum().sum())

print("\nData kosong setelah preprocessing:")
print(df.isnull().sum().sum())

print("\nJumlah baris duplikat:")
print(df.duplicated().sum())

display(df.head())

Data kosong sebelum preprocessing:
165

Data kosong setelah preprocessing:
102

Jumlah baris duplikat:
0

/tmp/ipykernel_7699/3060211435.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print(df_awal.replace("?", np.nan).isnull().sum().sum())

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NaN,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),NaN,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),NaN,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),NaN,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),NaN,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [ ]:
print("DATA SEBELUM PREPROCESSING")
print("Jumlah baris:", df_awal.shape[0])
print("Jumlah kolom:", df_awal.shape[1])

print("\nDATA SETELAH PREPROCESSING")
print("Jumlah baris:", df.shape[0])
print("Jumlah kolom:", df.shape[1])

DATA SEBELUM PREPROCESSING
Jumlah baris: 34
Jumlah kolom: 50

DATA SETELAH PREPROCESSING
Jumlah baris: 34
Jumlah kolom: 50

In [ ]:
df.to_csv(
    "/content/diabetes_hasil_preprocessing.csv",
    index=False
)

print("Dataset hasil preprocessing berhasil disimpan")

Dataset hasil preprocessing berhasil disimpan

In [ ]:
files.download(
    "/content/diabetes_hasil_preprocessing.csv"
)